### PR TITLE
Deprecate the package

### PR DESCRIPTION
**Pull request by dimitrisnl**
Change-type: patch
Signed-off-by: Dimitrios Lytras <dimitrios@balena.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Depends on:

- https://github.com/balena-io-modules/resin-event-log/pull/4 - DONE
- https://github.com/balena-io-modules/resin-mixpanel-client/pull/2 - DONE
- https://github.com/balena-io-modules/resin-universal-ga/pull/1 - DONE
- https://github.com/balena-io-modules/resin-universal-gosquared/pull/1 - DONE
- https://github.com/balena-io-modules/resin-universal-http-mock/pull/3 - DONE
- https://github.com/balena-io-modules/resin-universal-mixpanel/pull/1 - DONE

**Comment by dimitrisnl** [comment]
@resin-ci retest

**Comment by dimitrisnl** [comment]
@resin-ci retest

**Comment by dimitrisnl** [comment]
@nazrhom Can we remove the store-npm check from being required? I would love a review so people won't be confused by this deprecated package

**Comment by dimitrisnl** [comment]
Friendly ping @thgreasi

**Comment by thgreasi** [comment]
@dimitrisnl How about instead of deleting code, we just
* add a huge note in the README
  > Deprecated in favor of [resin-event-log](https://github.com/balena-io-modules/resin-event-log)
* and then [archive the repository](https://help.github.com/en/articles/archiving-a-github-repository) to make it readonly

Ideally the README change shouldn't cause an extra npm publish.
Alternatively we could just update the repo description with the above note.

**Comment by dimitrisnl** [comment]
I see, makes sense @thgreasi

**Comment by dimitrisnl** [comment]
How does it look @thgreasi  ?

**Review by thgreasi — APPROVED** [review]

**Comment by dimitrisnl** [comment]
@balena-ci  retest

**Comment by dimitrisnl** [comment]
@balena-ci retest

**Comment by dimitrisnl** [comment]
@nazrhom Hey, are my changes (.resinci.yml, package.json) enough to ensure that the CI won't try to publish this package?

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Pull request merged**
